### ISSUE TITLE
 Integrations -> Web

### ISSUE THREAD

**Issue by jacobvinzent** [qlik-oss/web-integration-examples#9]
I can not follow the steps below as I don't have  Integrations -> Web in my admin console. I don't have the main menu "Integration" at all.

To your left, select Integrations -> Web and create a new web integration, make sure you add http://127.0.0.1:1234 (or whatever URL is shown in your terminal above) to your whitelist

**Comment by peol** [comment]
In a local deployment of QSEoK (and which features are enabled) or QCS? QCS should have the feature toggled on globally, QSEoK in edge channel should as well. Not sure if the latest QSEoK stable has it enabled yet.

**Comment by jacobvinzent** [comment]
It is a local installation, using this:
https://github.com/ChristofSchwarz/qs_on_Kubernetes/blob/master/vagrantprovision/sh/4_qlik.sh

So it seems like it is not enabled on the stable version.

**Comment by peol** [comment]
@jacobvinzent Latest stable is from June 25th which would not contain web integrations. The edge channel should, though (and will be in the next stable).
